name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip build-essential \
          git zip unzip openjdk-17-jdk \
          libffi-dev libssl-dev \
          libzbar-dev libsqlite3-dev

    - name: Install pip packages
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: victory-app-debug
        path: bin/*.apk
